# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - develop

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    sed -i -e "s/\(\"version\":\\s\+\"\([0-9]\+\.\?\)\+\)/\1-pre.$BUILD_BUILDNUMBER/" package.json;
  displayName: 'Preview version'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: Npm@1
  inputs:
    command: custom
    customCommand: publish --tag next
    customEndpoint: 'npm_registry'
  displayName: 'Publish Pre-Package'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: Npm@1
  inputs:
    command: publish
    publishEndpoint: 'npm_registry'
  displayName: 'Publish Package'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
